"use client";

import React from "react";
import { AnalysisResult } from "@/types";
import styles from "./pdfTemplates.module.css";

interface Props {
  resumeText?: string;
  jobDescription?: string;
  targetRole?: string;
  result: AnalysisResult;
}

export default function CreativeTemplate({
  resumeText,
  jobDescription,
  targetRole,
  result,
}: Props) {
  return (
    <div className={styles.creativeContainer}>
      <div
        style={{
          display: "flex",
          gap: 16,
          alignItems: "center",
          marginBottom: 8,
        }}
      >
        <div className={styles.creativeBadge}>{result.score}</div>
        <div>
          <div style={{ fontSize: 20, fontWeight: 800 }}>
            {targetRole || "Resume Review"}
          </div>
          <div style={{ color: "#7c2d12", fontSize: 12 }}>
            {jobDescription ? "Tailored to the role" : "General"}
          </div>
        </div>
      </div>

      <div className={styles.creativeGrid}>
        <div>
          <h4 style={{ margin: "4px 0 8px 0" }}>Summary</h4>
          <p style={{ marginTop: 0, whiteSpace: "pre-wrap" }}>
            {result.summary}
          </p>

          <h4 style={{ marginTop: 12 }}>Key Rewrites</h4>
          {result.suggestions.slice(0, 4).map((s, i) => (
            <div key={i} style={{ marginBottom: 8 }}>
              <div style={{ fontWeight: 700 }}>{s.section}</div>
              <div style={{ color: "#4b2e2e" }}>{s.after}</div>
            </div>
          ))}
        </div>

        <aside className={styles.creativeAside}>
          <h4 style={{ marginTop: 0 }}>Strengths</h4>
          <ul>
            {result.strengths.map((s, i) => (
              <li key={i} style={{ marginBottom: 6 }}>
                {s}
              </li>
            ))}
          </ul>
          <h4 style={{ marginTop: 8 }}>Weaknesses</h4>
          <ul>
            {result.weaknesses.map((w, i) => (
              <li key={i} style={{ marginBottom: 6 }}>
                {w}
              </li>
            ))}
          </ul>
        </aside>
      </div>

      <div className={styles.small}>
        Creative template — Generated by ResumeLens
      </div>
    </div>
  );
}
