"use client";

import React from "react";
import { AnalysisResult } from "@/types";
import styles from "./pdfTemplates.module.css";

interface Props {
  resumeText?: string;
  jobDescription?: string;
  targetRole?: string;
  result: AnalysisResult;
}

export default function ExecutiveTemplate({
  jobDescription,
  targetRole,
  result,
}: Props) {
  return (
    <div className={styles.executiveContainer} style={{
      fontFamily: "'Times New Roman', Times, Georgia, serif",
      color: "#111827",
      background: "white",
      padding: "40px",
      lineHeight: 1.45,
      fontSize: "11pt",
    }}>
      <header style={{ textAlign: "center", marginBottom: "28px", borderBottom: "1.5px solid #111827", paddingBottom: "18px" }}>
        <h1 style={{ fontSize: "20pt", fontWeight: "bold", textTransform: "uppercase", letterSpacing: "0.5px", color: "#7a1c1c", margin: "0 0 6px 0" }}>
          {targetRole || "Resume Analysis"}
        </h1>
        <div style={{ fontSize: "10pt", color: "#4b5563", fontStyle: "italic", marginBottom: "8px" }}>
          {jobDescription ? "Evaluation against Job Description" : "General Resume Evaluation"}
        </div>
        <div style={{ display: "inline-flex", flexDirection: "column", alignItems: "center", marginTop: "4px" }}>
          <div style={{ fontSize: "24pt", fontWeight: "bold", color: "#7a1c1c" }}>
            {result.score} / 100
          </div>
          <div style={{ fontSize: "8pt", textTransform: "uppercase", letterSpacing: "1px", color: "#6b7280" }}>
            Overall Score
          </div>
        </div>
      </header>

      <section style={{ marginBottom: "24px" }}>
        <h2 style={{ fontSize: "11pt", fontWeight: "bold", textTransform: "uppercase", fontVariant: "small-caps", letterSpacing: "1px", borderBottom: "1px solid #111827", paddingBottom: "2px", marginBottom: "10px" }}>
          Executive Summary
        </h2>
        <p style={{ margin: 0, fontSize: "11pt", color: "#1f2937", textAlign: "justify" }}>
          {result.summary}
        </p>
      </section>

      <section style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "24px", marginBottom: "24px" }}>
        <div>
          <h3 style={{ fontSize: "11pt", fontWeight: "bold", textTransform: "uppercase", fontVariant: "small-caps", letterSpacing: "1px", borderBottom: "1px solid #111827", paddingBottom: "2px", marginBottom: "10px" }}>
            Key Strengths
          </h3>
          <ul style={{ margin: 0, paddingLeft: "18px", fontSize: "10.5pt", color: "#1f2937" }}>
            {result.strengths.map((s, i) => (
              <li key={i} style={{ marginBottom: "4px" }}>{s}</li>
            ))}
          </ul>
        </div>
        <div>
          <h3 style={{ fontSize: "11pt", fontWeight: "bold", textTransform: "uppercase", fontVariant: "small-caps", letterSpacing: "1px", borderBottom: "1px solid #111827", paddingBottom: "2px", marginBottom: "10px" }}>
            Areas to Improve
          </h3>
          <ul style={{ margin: 0, paddingLeft: "18px", fontSize: "10.5pt", color: "#1f2937" }}>
            {result.weaknesses.map((w, i) => (
              <li key={i} style={{ marginBottom: "4px" }}>{w}</li>
            ))}
          </ul>
        </div>
      </section>

      <section style={{ marginBottom: "24px" }}>
        <h2 style={{ fontSize: "11pt", fontWeight: "bold", textTransform: "uppercase", fontVariant: "small-caps", letterSpacing: "1px", borderBottom: "1px solid #111827", paddingBottom: "2px", marginBottom: "12px" }}>
          Actionable Suggestions
        </h2>
        <div>
          {result.suggestions.slice(0, 5).map((s, i) => (
            <div key={i} style={{ marginBottom: "14px", borderBottom: "1px solid #e5e7eb", paddingBottom: "10px" }}>
              <div style={{ fontWeight: "bold", color: "#111827", fontSize: "10.5pt" }}>{s.section}</div>
              <div style={{ color: "#6b7280", marginTop: "4px", fontSize: "10pt" }}>
                <strong>Original:</strong> {s.before}
              </div>
              <div style={{ color: "#7a1c1c", marginTop: "2px", fontSize: "10pt", fontWeight: 500 }}>
                <strong>Recommendation:</strong> {s.after}
              </div>
            </div>
          ))}
        </div>
      </section>

      <footer style={{ marginTop: "32px", borderTop: "1px solid #e5e7eb", paddingTop: "8px", fontSize: "8pt", textTransform: "uppercase", color: "#9ca3af", letterSpacing: "0.5px" }}>
        Generated by ResumeLens • Seniority/Executive Audit Report
      </footer>
    </div>
  );
}
