"use client";

import React from "react";
import { AnalysisResult } from "@/types";
import styles from "./pdfTemplates.module.css";

interface Props {
  resumeText?: string;
  jobDescription?: string;
  targetRole?: string;
  result: AnalysisResult;
}

export default function ModernTemplate({
  jobDescription,
  targetRole,
  result,
}: Props) {
  return (
    <div className={styles.modernContainer}>
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          marginBottom: 14,
        }}
      >
        <div>
          <h1 style={{ margin: 0, fontSize: 22 }}>
            {targetRole || "Resume Review"}
          </h1>
          <div style={{ color: "#6b7280", fontSize: 12 }}>
            {jobDescription ? "Tailored to job description" : "General review"}
          </div>
        </div>
        <div style={{ textAlign: "right" }}>
          <div
            style={{
              fontSize: 26,
              fontWeight: 800,
              color:
                result.score >= 75
                  ? "#047857"
                  : result.score >= 55
                    ? "#92400e"
                    : "#7a2020",
            }}
          >
            {result.score}
          </div>
          <div style={{ fontSize: 11, color: "#9ca3af" }}>Overall Score</div>
        </div>
      </div>

      <div className={styles.grid}>
        <div>
          <h3 style={{ margin: "0 0 8px 0" }}>Summary</h3>
          <p style={{ marginTop: 0, whiteSpace: "pre-wrap", color: "#111827" }}>
            {result.summary}
          </p>

          <h4 style={{ marginTop: 12 }}>Suggestions</h4>
          {(result.suggestions || []).slice(0, 6).map((s, i) => (
            <div
              key={i}
              style={{
                marginBottom: 10,
                paddingBottom: 8,
                borderBottom: "1px dashed #f1f5f9",
              }}
            >
              <div style={{ fontWeight: 700 }}>{s.section}</div>
              <div style={{ color: "#374151", marginTop: 6 }}>
                <strong>After:</strong> {s.after}
              </div>
            </div>
          ))}
        </div>

        <aside className={styles.aside}>
          <h4 style={{ marginTop: 0 }}>Strengths</h4>
          <ul className={styles.asideList}>
            {(result.strengths || []).map((s, i) => (
              <li key={i} style={{ marginBottom: 6 }}>
                {s}
              </li>
            ))}
          </ul>

          <h4 style={{ marginTop: 10 }}>Weaknesses</h4>
          <ul className={styles.asideList}>
            {(result.weaknesses || []).map((w, i) => (
              <li key={i} style={{ marginBottom: 6 }}>
                {w}
              </li>
            ))}
          </ul>
        </aside>
      </div>

      <div className={styles.small}>
        Generated by ResumeLens • {new Date().getFullYear()}
      </div>
    </div>
  );
}
