"use client";

import React from "react";
import { AnalysisResult } from "@/types";
import { DESIGN_TOKENS } from "@/lib/designTokens";
import styles from "./pdfTemplates.module.css";

interface Props {
  resumeText?: string;
  jobDescription?: string;
  targetRole?: string;
  result: AnalysisResult;
}

export default function ProfessionalTemplate({
  jobDescription,
  targetRole,
  result,
}: Props) {
  const tokens = DESIGN_TOKENS.professional;

  return (
    <div className={styles.professionalContainer} style={{ fontFamily: tokens.fontFamily, color: tokens.textColor }}>
      <header className={styles.header}>
        <div>
          <div className={styles.headerTitle} style={{ color: tokens.primaryColor }}>
            {targetRole || "Resume Review"}
          </div>
          <div className={styles.headerMeta}>
            {jobDescription ? "Tailored to job description" : "General review"}
          </div>
        </div>
        <div style={{ textAlign: "right" }}>
          <div
            className={styles.score}
            style={{
              color:
                result.score >= 75
                  ? "#115e59"
                  : result.score >= 55
                    ? "#92400e"
                    : "#7a2020",
            }}
          >
            {result.score}
          </div>
          <div className={styles.small}>Overall Score</div>
        </div>
      </header>

      <section className={styles.section}>
        <h2 className={styles.sectionH2} style={{ color: tokens.primaryColor }}>Summary</h2>
        <p className={styles.sectionP}>{result.summary}</p>
      </section>

      <section className={styles.twoCol}>
        <div className={styles.col}>
          <h3 style={{ fontSize: 13, marginBottom: 8, color: tokens.primaryColor, fontWeight: "bold" }}>Strengths</h3>
          <ul className={styles.list}>
            {(result.strengths || []).map((s, i) => (
              <li key={i} className={styles.listItem}>
                {s}
              </li>
            ))}
          </ul>
        </div>
        <div className={styles.col}>
          <h3 style={{ fontSize: 13, marginBottom: 8, color: tokens.primaryColor, fontWeight: "bold" }}>Areas to Improve</h3>
          <ul className={styles.list}>
            {(result.weaknesses || []).map((w, i) => (
              <li key={i} className={styles.listItem}>
                {w}
              </li>
            ))}
          </ul>
        </div>
      </section>

      <section className={styles.section}>
        <h3 style={{ fontSize: 13, marginBottom: 8, color: tokens.primaryColor, fontWeight: "bold" }}>Top Suggestions</h3>
        <div>
          {(result.suggestions || []).slice(0, 6).map((s, i) => (
            <div key={i} className={styles.suggestion}>
              <div className={styles.suggestionHeader}>{s.section}</div>
              <div className={styles.suggestionBefore}>
                <strong>Before:</strong> {s.before}
              </div>
              <div className={styles.suggestionAfter}>
                <strong>After:</strong> {s.after}
              </div>
            </div>
          ))}
        </div>
      </section>

      <footer className={styles.footer}>Generated by ResumeLens</footer>
    </div>
  );
}
