import logger from "@/lib/logger";
import { NextRequest, NextResponse } from "next/server";
import playwright from "playwright";
import { createAdminClient } from "../../../lib/supabase";
import { createRouteHandlerClient } from "@/lib/supabase";
import { cookies } from "next/headers";

export const runtime = "nodejs";
export const maxDuration = 120;

function buildHtml(template: string, payload: any) {
  const { result, targetRole, jobDescription } = payload;
  const scoreColor =
    result.score >= 75 ? "#047857" : result.score >= 55 ? "#92400e" : "#7a2020";

  // Basic styles used across templates
  const base = `
    body{font-family:Inter,Arial,sans-serif; margin:0; padding:20px; background:white; color:#0b1220}
    .container{max-width:800px; margin:0 auto}
    h1{margin:0;font-size:22px}
    .score{font-size:40px;font-weight:800;color:${scoreColor}}
    .section{margin-top:14px}
    .muted{color:#6b7280;font-size:13px}
    .list{margin:6px 0 0 18px}
  `;

  // Template-specific HTML
  if (template === "classic") {
    return `<!doctype html><html><head><meta charset="utf-8"><style>${base} h1{font-family:Georgia,serif}</style></head><body><div class="container"><header style="display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #eee;padding-bottom:12px"><div><h1>${escapeHtml(
      targetRole || "Resume Review",
    )}</h1><div class="muted">${jobDescription ? "Tailored to job description" : "General review"}</div></div><div style="text-align:right"><div class="score">${result.score}</div><div class="muted">Overall Score</div></div></header><main><section class="section"><h2>Summary</h2><div class="muted">${escapeHtml(result.summary)}</div></section><section class="section" style="display:flex;gap:24px"><div style="flex:1"><h3>Strengths</h3><ul class="list">${(result.strengths || []).map((s: string) => `<li>${escapeHtml(s)}</li>`).join("")}</ul></div><div style="flex:1"><h3>Areas to Improve</h3><ul class="list">${(result.weaknesses || []).map((w: string) => `<li>${escapeHtml(w)}</li>`).join("")}</ul></div></section><section class="section"><h3>Top Suggestions</h3>${(
      result.suggestions || []
    )
      .slice(0, 6)
      .map(
        (s: any) =>
          `<div style="margin-bottom:12px"><div style="font-weight:700">${escapeHtml(s.section)}</div><div style="color:#6b7280"><strong>Before:</strong> ${escapeHtml(s.before)}</div><div style="margin-top:6px"><strong>After:</strong> ${escapeHtml(s.after)}</div></div>`,
      )
      .join("")}</section></main><footer style="margin-top:22px;color:#6b7280;font-size:12px">Generated by ResumeLens</footer></div></body></html>`;
  }

  // creative
  return `<!doctype html><html><head><meta charset="utf-8"><style>${base} body{background:#fffaf6} .badge{width:72px;height:72px;border-radius:10px;background:#ffedd5;display:flex;align-items:center;justify-content:center;font-size:20px;font-weight:800;color:#c2410c}</style></head><body><div class="container"><div style="display:flex;gap:16px;align-items:center;margin-bottom:8px"><div class="badge">${result.score}</div><div><div style="font-size:20px;font-weight:800">${escapeHtml(targetRole || "Resume Review")}</div><div style="color:#7c2d12;font-size:12px">${jobDescription ? "Tailored to the role" : "General"}</div></div></div><div style="display:grid;grid-template-columns:1fr 300px;gap:16px"><div><h4 style="margin:4px 0 8px 0">Summary</h4><p style="margin-top:0">${escapeHtml(result.summary)}</p><h4 style="margin-top:12px">Key Rewrites</h4>${(
    result.suggestions || []
  )
    .slice(0, 4)
    .map(
      (s: any) =>
        `<div style="margin-bottom:8px"><div style="font-weight:700">${escapeHtml(s.section)}</div><div style="color:#4b2e2e">${escapeHtml(s.after)}</div></div>`,
    )
    .join("")}</div><aside style="background:#fff7ed;padding:12px;border-radius:8px"><h4 style="margin-top:0">Strengths</h4><ul class="list">${(result.strengths || []).map((s: string) => `<li>${escapeHtml(s)}</li>`).join("")}</ul><h4 style="margin-top:8px">Weaknesses</h4><ul class="list">${(result.weaknesses || []).map((w: string) => `<li>${escapeHtml(w)}</li>`).join("")}</ul></aside></div><div style="margin-top:18px;font-size:11px;color:#6b7280">Creative template — Generated by ResumeLens</div></div></body></html>`;
}

function escapeHtml(s: any) {
  if (s === null || s === undefined) return "";
  return String(s)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

export async function POST(req: NextRequest) {
  // ── Auth check — prevents anonymous DoS via Playwright ────
  const supabase = createRouteHandlerClient({ cookies });
  const {
    data: { session },
  } = await supabase.auth.getSession();

  if (!session) {
    return NextResponse.json(
      { success: false, error: "Not authenticated" },
      { status: 401 },
    );
  }

  try {
    const body = await req.json();
    const { template = "classic" } = body;

    const html = buildHtml(template, body);

    const browser = await playwright.chromium.launch({
      args: ["--no-sandbox"],
    });
    const context = await browser.newContext({
      viewport: { width: 1200, height: 800 },
    });
    const page = await context.newPage();
    await page.setContent(html, { waitUntil: "networkidle" });

    const pdf = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: { top: "16mm", bottom: "16mm", left: "14mm", right: "14mm" },
    });

    await browser.close();

    // Try to upload the PDF to Supabase Storage and return a public URL.
    try {
      const adminClient = createAdminClient();
      const bucket = process.env.SUPABASE_PDF_BUCKET || "pdfs";
      const fileName = `exports/${Date.now()}-${template}.pdf`;

      const { error: uploadError } = await adminClient.storage
        .from(bucket)
        .upload(fileName, pdf, { contentType: "application/pdf" });

      if (uploadError) {
        logger.warn(
          "Supabase upload error:",
          uploadError.message || uploadError,
        );
        throw uploadError;
      }

      const { data: urlData } = await adminClient.storage
        .from(bucket)
        .getPublicUrl(fileName);

      // If the bucket is public, getPublicUrl will return a usable URL.
      if (urlData?.publicUrl) {
        return NextResponse.json(
          { success: true, url: urlData.publicUrl },
          { status: 200 },
        );
      }

      // Fallback: create a signed URL (valid for 24 hours) so private buckets still work.
      try {
        const expiresIn = 60 * 60 * 24; // 24 hours
        const { data: signedData, error: signedErr } = await adminClient.storage
          .from(bucket)
          .createSignedUrl(fileName, expiresIn);

        if (signedErr || !signedData?.signedUrl) {
          logger.warn(
            "Supabase createSignedUrl error:",
            signedErr?.message || signedErr,
          );
          throw signedErr || new Error("Failed to create signed URL");
        }

        return NextResponse.json(
          { success: true, url: signedData.signedUrl, signed: true },
          { status: 200 },
        );
      } catch (e) {
        logger.warn("Signed URL fallback failed:", e);
        throw e;
      }
    } catch (uploadErr) {
      // If upload fails, fall back to returning the PDF directly.
      return new NextResponse(pdf as unknown as BodyInit, {
        status: 200,
        headers: {
          "Content-Type": "application/pdf",
          "Content-Disposition": `attachment; filename="ResumeLens-${template}.pdf"`,
        },
      });
    }
  } catch (err: any) {
    return NextResponse.json(
      { success: false, error: String(err?.message || err) },
      { status: 500 },
    );
  }
}
